### ISSUE TITLE
RIS Index Encoding Guide on CESNI website

### ISSUE THREAD

**Issue by ChristophPlasil** [cesniti/ris_public_files#4] opened 2020-02-10 16:13 UTC
Salut Jean-Noël,

I got the question below.

Jonas is right, that the RIS Index Encoding Guide is not available on ris.cesni.eu nor secure.cesni.eu.

We shall make it available also on the public part. Originally there was an own section for the JTF RIS Index on ris.eu as well as eg.ris.eu which is not there anymore in the new framework.

Maybe another sub-page for the RIS Index is necessary.

What I also noticed is that on the page “https://ris.cesni.eu/332-en.html“ if you scroll down to “IMPLEMENTATION STATUS:” all the referred documents below this headline are not available.

Many thanks for your efforts, best wishes, Christoph

-----------------------------

Hello Christophe

I was searching in the CESNI document repository and didn’t quite found what I was searching for.
Will they renew this website in time? 

Where can I find the RIS-index Encoding Guide that we discussed about in the last meeting?

Best regards
Jonas.

Jonas Roels
Head of Software Department
IALA Industrial Member

 
     
ALSIC bvba
Derbystraat 25
9051 Sint-Denijs-Westrem
Tel : +32-9-265.91.17
GSM: +32-473-95.22.62
jonas.roels@alsic.be

**Comment by jnschilling** [comment] 2020-02-11 14:49
> Jonas is right, that the RIS Index Encoding Guide is not available on ris.cesni.eu nor secure.cesni.eu.
> We shall make it available also on the public part. Originally there was an own section for the JTF RIS Index on ris.eu as well as eg.ris.eu which is not there anymore in the new framework.
> Maybe another sub-page for the RIS Index is necessary.

@ChristophPlasil
Indeed Christoph, this is intended to have a new section called 'reference data', I will work on it in the coming weeks, support will be welcome ! In the meantime, all documents are available in the JTF RIS index section of the secure.cesni.eu\CESNI_TI\Archives\JTF_RIS_Index
I will create a project to make this reference data page come to life

@ChristophPlasil 
>What I also noticed is that on the page “https://ris.cesni.eu/332-en.html if you scroll down to >“IMPLEMENTATION STATUS:” all the referred documents below this headline are not available.

links were dead indeed, I resolved the issue by adding the files and updating the links
Let me know if everything works as intended so I can close the issue

**Comment by ChristophPlasil** [comment] 2020-02-12 16:58
@jnschilling Many thanks!
I think the dump of the JTF Section was made before I uploaded the RIS Index Encoding Guide 3.0 at Xmas last year. Therefore please find the documents attached. Could you make them available in the planned new section?
[2019_12_24_RIS_Index_template_v3p0.xlsx](https://github.com/cesniti/ris_public_files/files/4193646/2019_12_24_RIS_Index_template_v3p0.xlsx)
[2019_12_24_RIS-Index_Encoding_Guide_ANNEX_1_FAQ_v3p0.docx](https://github.com/cesniti/ris_public_files/files/4193648/2019_12_24_RIS-Index_Encoding_Guide_ANNEX_1_FAQ_v3p0.docx)
[2019_12_24_RIS_Index_Encoding_Guide_v3p0.pdf](https://github.com/cesniti/ris_public_files/files/4193649/2019_12_24_RIS_Index_Encoding_Guide_v3p0.pdf)

**Comment by ChristophPlasil** [comment] 2020-03-27 14:14
[](url)

**Comment by ChristophPlasil** [comment] 2020-03-27 14:19
There is an editorial correction of the RIS Index Encoding Guide 3.0 rev.1:
"Correction of typo in chapter 3.1 (priority objects _list)"
[2019_12_24_RIS_Index_Encoding_Guide_v3p0 rev.1.pdf](https://github.com/cesniti/ris_public_files/files/4393988/2019_12_24_RIS_Index_Encoding_Guide_v3p0.rev.1.pdf)

**Comment by ChristophPlasil** [comment] 2020-09-23 09:12
Salut JN,

there was a type in the RIS Index Encoding Guide where the function_code of "berths_9" had to be corrected (an 's' was missing). Please update the RIS Index Encoding Guide Documents and Excel template to ".rev2" at all locations.
These documents are provided here: https://ris.cesni.eu/332-en.html (at least)

Many thanks, Christoph

[2019_12_24_RIS_Index_Encoding_Guide+template_v3p0 rev.2.zip](https://github.com/cesniti/ris_public_files/files/5266903/2019_12_24_RIS_Index_Encoding_Guide%2Btemplate_v3p0.rev.2.zip)
[2019_12_24_RIS_Index_Encoding_Guide_v3p0 rev.2.docx](https://github.com/cesniti/ris_public_files/files/5266908/2019_12_24_RIS_Index_Encoding_Guide_v3p0.rev.2.docx)
[2019_12_24_RIS_Index_Encoding_Guide_v3p0 rev.2.pdf](https://github.com/cesniti/ris_public_files/files/5266950/2019_12_24_RIS_Index_Encoding_Guide_v3p0.rev.2.pdf)
[2019_12_24_RIS_Index_template_v3p0 rev.2.xlsx](https://github.com/cesniti/ris_public_files/files/5266973/2019_12_24_RIS_Index_template_v3p0.rev.2.xlsx)

**Comment by jnschilling** [comment] 2020-09-24 15:36
the rev2 of the files is now included
have a good day, JN

**Closed as completed by jnschilling** 2020-09-24 15:36 UTC
Labels: bug
